### PR TITLE
Add lua resty and openjson packages

### PR DESCRIPTION
**Pull request by demonspork**
Needed to run a lua google oauth2 script.

https://github.com/linuxserver/docker-nginx/issues/22

### CODE REVIEW

**Comment by j0nnymoe** [comment]
jenkins test this please

**Comment by aptalca** [comment]
Why 5.1 and not 5.3?

Did you test installing those packages and making sure that they work?
Last time you requested this, later you changed your mind and said they weren't needed (I believe it was you)

**Comment by demonspork** [comment]
I have tested, I did request these before and thought they had been added,
but they weren't there a few months later after an update and I had to add
them back.

I can test 5.3. 5.1 was what I had documented to install back in September,
no idea if it was a requirement or just what I ended up using.


On Jan 27, 2018 7:49 PM, "aptalca" <notifications@github.com> wrote:

Why 5.1 and not 5.3?

Did you test installing those packages and making sure that they work?
Last time you requested this, later you changed your mind and said they
weren't needed (I believe it was you)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/linuxserver/docker-nginx/pull/23#issuecomment-361031332>,
or mute the thread

**Comment by demonspork** [comment]
I tested 5.3, recreated the container and manually did apk add lua5.3-cjson and resty-http but I got errors that cjson was not found:
        no field package.preload['cjson']
        no file './cjson.lua'
        no file '/usr/share/luajit-2.1.0-beta3/cjson.lua'
        no file '/usr/local/share/lua/5.1/cjson.lua'
        no file '/usr/local/share/lua/5.1/cjson/init.lua'
        no file '/usr/share/lua/5.1/cjson.lua'
        no file '/usr/share/lua/5.1/cjson/init.lua'
        no file './cjson.so'
        no file '/usr/local/lib/lua/5.1/cjson.so'
        no file '/usr/lib/lua/5.1/cjson.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'


Like it is referencing lua 5.1 for all the packages. I couldn't find any mention of the lua libs/modules in the nginx config files.

So for now I can only get by with 5.1 for the oauth2 script I am using.

**Comment by aptalca** [comment]
I'm not convinced this works or is necessary.

For now I'll close this. The packages can be installed via mapping an init file `-v /path/to/90-config:/etc/cont-init.d/90-config` with the contents

```
#!/usr/bin/with-contenv bash

apk add --no-cache <packages of interest>
```

**Comment by demonspork** [comment]
That is neat. I didn't know I could do that. Thank you very much!

**Pull request closed without merging**
